blank_issues_enabled: true
contact_links:
  - name: .NET Aspire Discussions
    url: https://github.com/dotnet/aspnetcore/discussions
    about: For other types of questions, consider using Discussions.
  - name: Issue Management Policies
    url: https://aka.ms/aspnet/issue-policies
    about: More information on our issue management policies is available here.
