name: Refresh Manifests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # 8am PST (16:00 UTC) - same schedule as API review

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-and-pr:
    runs-on: windows-latest # Using Windows because the script uses PowerShell and build.cmd
    if: ${{ github.repository_owner == 'dotnet' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run RefreshManifests Script
        shell: pwsh
        env:
          CI: false
        run: |
          ./eng/refreshManifests.ps1

      - name: Create or update pull request
        uses: dotnet/actions-create-pull-request@e8d799aa1f8b17f324f9513832811b0a62f1e0b1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-manifests
          base: main
          commit-message: "[Automated] Update Playground Manifests"
          labels: |
            area-app-model
            area-engineering-systems
          title: "[Automated] Update Manifests"
          body: "Auto-generated update to refresh the manifests."
